apiVersion: apps/v1
kind: Deployment
metadata:
  name: vahannetra-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vahannetra-frontend
  template:
    metadata:
      labels:
        app: vahannetra-frontend
    spec:
      containers:
        - name: frontend
          image: vahannetra-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vahannetra-frontend
spec:
  selector:
    app: vahannetra-frontend
  ports:
    - port: 3000
      targetPort: 3000
