from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def _draw_bar_chart(
    pdf: canvas.Canvas, x: float, y: float, width: float, values: list[float]
) -> None:
    if not values:
        return
    max_v = max(values) or 1
    bar_w = width / max(len(values), 1)
    for i, val in enumerate(values):
        h = (val / max_v) * 20 * mm
        pdf.setFillColor(colors.HexColor("#22d3ee"))
        pdf.rect(x + i * bar_w, y, bar_w - 1.5, h, fill=1, stroke=0)


def render_inspection_report(payload: dict) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    pdf.setAuthor("Vahannetra AI")
    pdf.setTitle(f"Inspection Report {payload['inspection_id']}")
    pdf.setSubject("Vehicle Damage Assessment")

    width, height = A4
    y = height - 18 * mm

    # Header
    pdf.setFillColor(colors.HexColor("#0f172a"))
    pdf.rect(0, height - 24 * mm, width, 24 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(12 * mm, height - 12 * mm, "VAHANNETRA AI INSPECTION REPORT")
    pdf.setFont("Helvetica", 9)
    pdf.drawRightString(
        width - 12 * mm, height - 12 * mm, f"ID: {payload['inspection_id']}"
    )

    y -= 14 * mm
    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica", 10)
    lines = [
        f"Vehicle: {payload['vehicle']['plate']} | {payload['vehicle']['model']} | {payload['vehicle']['type']}",
        f"Inspected At: {payload['vehicle']['inspected_at']}",
        f"Health Score: {payload['health_score']}",
        f"Triage Category: {payload['triage_category']}",
        f"Total Findings: {len(payload['findings'])}",
    ]
    for line in lines:
        pdf.drawString(12 * mm, y, line)
        y -= 5 * mm

    # Summary chart
    y -= 4 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(12 * mm, y, "Severity confidence chart")
    y -= 22 * mm
    _draw_bar_chart(
        pdf,
        12 * mm,
        y,
        80 * mm,
        [float(item.get("confidence", 0.0)) * 100 for item in payload["findings"][:8]],
    )

    # Findings table
    y -= 10 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(12 * mm, y, "Findings table")
    y -= 6 * mm
    pdf.setFont("Helvetica", 9)
    pdf.drawString(12 * mm, y, "Type")
    pdf.drawString(55 * mm, y, "Severity")
    pdf.drawString(85 * mm, y, "Confidence")
    pdf.drawString(120 * mm, y, "Estimate")
    y -= 4 * mm
    pdf.line(12 * mm, y, width - 12 * mm, y)
    y -= 4 * mm

    for finding in payload["findings"]:
        if y < 28 * mm:
            pdf.showPage()
            y = height - 20 * mm
            pdf.setFont("Helvetica", 9)
        pdf.drawString(12 * mm, y, str(finding["type"]))
        pdf.drawString(55 * mm, y, str(finding["severity"]))
        pdf.drawString(85 * mm, y, f"{round(float(finding['confidence']) * 100, 1)}%")
        pdf.drawString(
            120 * mm, y, f"₹{finding['estimate_min']} - ₹{finding['estimate_max']}"
        )
        y -= 5 * mm

    # Footer with blockchain hash
    pdf.setStrokeColor(colors.HexColor("#94a3b8"))
    pdf.line(12 * mm, 16 * mm, width - 12 * mm, 16 * mm)
    pdf.setFont("Helvetica", 8)
    pdf.drawString(
        12 * mm, 11 * mm, "Generated by Vahannetra AI | A4 Professional Report"
    )
    pdf.drawRightString(
        width - 12 * mm,
        11 * mm,
        f"Blockchain SHA-256: {payload.get('blockchain_hash', 'n/a')[:20]}...",
    )

    pdf.showPage()
    pdf.save()
    return buffer.getvalue()
